---
- name: "(Setup: NGINX Open Source) Enable NGINX Open Source Status"
  template:
    src: "templates/http/stub_status.conf.j2"
    dest: "{{ nginx_status_location }}"
  when: nginx_type == "opensource"
  notify: "(Handler: All OSs) Reload NGINX"

- name: "(Setup: NGINX Plus) Enable NGINX Plus Status"
  template:
    src: "templates/http/stub_status.conf.j2"
    dest: "{{ nginx_status_location }}"
  when: nginx_type == "plus"
  notify: "(Handler: All OSs) Reload NGINX"
